### PR TITLE
Improved sorting of emissions in CLI

### PR DESCRIPTION
**Pull request by bmaupin**
Before:

    $ toutv list | head
    2424966779 - 1001 vies
    2424966602 - 20 ans de bloopers
    2424967198 - 24|60 Hors série
    1735242576 - 30 vies
    2424966763 - 7$ par jour
    2424966778 - 7ème ciel
    2183873619 - 8e feu : Les Autochtones et le Canada
    2424966808 - Agent secret
    2424966581 - Amour amour
    1954020558 - Animo
    $ toutv list | tail
    2424967167 - Zora la rousse
    2424966776 - Zugzwang
    2424967032 - À grands coups d'amour pour Gerry : 25 ans plus tard
    2321205822 - À l'année prochaine
    2424966352 - À l'horizon
    2424967051 - À l'épreuve d'une tribu
    2424966800 - Ça commence aujourd'hui
    2424967087 - Ça fait un bye
    2424966961 - Émilie
    2424966740 - Ô divin bovin

After:

    $ toutv list | head
    2424966779 - 1001 vies
    2424966602 - 20 ans de bloopers
    2424967198 - 24|60 Hors série
    1735242576 - 30 vies
    2424966778 - 7ème ciel
    2424966763 - 7$ par jour
    2183873619 - 8e feu : Les Autochtones et le Canada
    2424966808 - Agent secret
    2424967032 - À grands coups d'amour pour Gerry : 25 ans plus tard
    2201426010 - Aïcha
    $ toutv list | tail
    2424967046 - Yaya et Zouk
    2424966214 - Yes sir! Madame
    2424967163 - Yoko
    2424967170 - Zarafa
    2424966868 - Zigby
    2424966495 - Zinneke
    2424966245 - Zone Doc
    2424966841 - Zoobabu
    2424967167 - Zora la rousse
    2424966776 - Zugzwang

### CODE REVIEW

**Comment by bmaupin** [comment]
> Should we move the call to locale.setlocale(locale.LC_ALL, "") at the beginning of the program, so that we use the user's settings (e.g. for times and dates) everywhere?

Fine by me. I put it near the code that uses it because I wasn't sure where else to put it. Where specifically do you think it should go? At the top of the App class perhaps?

**Comment by simark** [comment]
> Fine by me. I put it near the code that uses it because I wasn't sure where else to put it. Where specifically do you think it should go? At the top of the App class perhaps?

I'd say either at the beginning of run (the function) or App.run.

**Comment by bmaupin** [comment]
How does that look?

**Comment by simark** [comment]
LGTM!

**Comment by bvanheu** [comment]
TOO LATE but what about using LC_COLLATE instead of LC_ALL which should be used for sorting and stuff?

**Comment by eepp** [comment]
> TOO LATE

Damn, too bad we're only allowed one commit/month with Git. I hate open source.

**Comment by simark** [comment]
> TOO LATE but what about using LC_COLLATE instead of LC_ALL which should be used for sorting and stuff?

For that particular issue, we only need LC_COLLATE, but I think it's not bad if other things, such as dates and times, are displayed according to the user's locale.

**Comment by bvanheu** [comment]
> Damn, too bad we're only allowed one commit/month with Git. I hate open source.

NEED. PERFECT. COMMIT HISTORY.

> For that particular issue, we only need LC_COLLATE, but I think it's not bad if other things, such as dates and times, are displayed according to the user's locale.

Alright, I guess I misunderstood the documentation:

> This sets the locale for all categories to the user’s default setting (typically specified in the LANG environment variable).

I thought it would overwrite each locale categories to be set to $LANG, breaking the purpose of locales :p

**Pull request merged**
