### PR TITLE
Download episodes in order

### PR DESCRIPTION
**Pull request by bmaupin**
Before:

    $ toutv fetch Peanuts
    Peanuts.S2015E1037.Sally.1325...    80.5 MiB   49/49 [####################] 100%
    Peanuts.S2015E1052.Neige.1325...    74.5 MiB   45/45 [####################] 100%
    Peanuts.S2015E1043.Amour.dans...    67.1 MiB   41/41 [####################] 100%
    Peanuts.S2015E1042.Un.peu.d'a...    74.6 MiB   45/45 [####################] 100%
    Peanuts.S2016E1049.Un.bon.chi...    68.7 MiB   42/42 [####################] 100%
    Peanuts.S2016E1036.Tennis.132...    85.4 MiB   51/51 [####################] 100%
    Peanuts.S2016E1051.Bon.à.rien...    75.2 MiB   45/45 [####################] 100%
    Peanuts.S2015E1058.On.tente.s...    69.3 MiB   42/42 [####################] 100%

After:

    $ toutv fetch Peanuts
    Peanuts.S2015E1037.Sally.1325...    80.5 MiB   49/49 [####################] 100%
    Peanuts.S2015E1042.Un.peu.d'a...    74.6 MiB   45/45 [####################] 100%
    Peanuts.S2015E1043.Amour.dans...    67.1 MiB   41/41 [####################] 100%
    Peanuts.S2015E1052.Neige.1325...    74.5 MiB   45/45 [####################] 100%
    Peanuts.S2015E1058.On.tente.s...    69.3 MiB   42/42 [####################] 100%
    Peanuts.S2016E1036.Tennis.132...    85.4 MiB   51/51 [####################] 100%
    Peanuts.S2016E1049.Un.bon.chi...    68.7 MiB   42/42 [####################] 100%
    Peanuts.S2016E1051.Bon.à.rien...    75.2 MiB   45/45 [####################] 100%

### CODE REVIEW

**Comment by bmaupin** [comment]
> Since this is duplicated from _print_list_episodes, perhaps you could extract it and use it in both places?

Done. How does that look?

**Comment by bmaupin** [comment]
> You can achieve the same thing more cleanly by using sorted():
>
>     for episode in sorted(episodes.values(), key=key_func):
>         ...

Good point. How about now?

**Comment by simark** [comment]
It LGTM.  I'll let others have a look.  Feel free to ping in 2-3 days if there is not more feedback.

Thanks a lot, it's appreciated!

**Comment by simark** [comment]
Thanks!

**Comment by eepp** [comment]
This code will probably change soon with pytoutv 3 anyway, but in the meantime if it works, why not.

At least let's remember the intention for the next version.

**Pull request merged**
