### PR TITLE
Print date according to user's locale

### PR DESCRIPTION
**Pull request by simark**
With LANG=fr_CA.UTF-8:

  * Air date: 2015-12-31

With LANG=en_CA.UTF-8:

  * Air date: 15-12-31

### CODE REVIEW

**Comment by simark** [comment]
Here is an example of how we could use the locale for displaying the date differently.  Honestly, I don't really like the en_CA result.  I wish there was a way to display it automatically in a "textual" way, like:

* fr: 31 déc 2015
* en: Dec 31st, 2015

Quelque chose du genre.

**Comment by bvanheu** [comment]
Then what about going with ISO8601 yyyy-mm-dd ?

**Comment by bmaupin** [comment]
> Then what about going with ISO8601 yyyy-mm-dd ?

That has my vote, for whatever it's worth.

**Comment by simark** [comment]
> Then what about going with ISO8601 yyyy-mm-dd ?

That's what is printed right now, so let's just keep it like this.

**Pull request closed without merging**
